n1 = input('Digite algo: ')
n2 = type(n1)
n3 = n1.isnumeric()
n4 = n1.isalpha()
n5 = n1.isalnum()
print(f'Tipo primitivo do valor digitado: {n2}')
print(f'O valor digitado é numeral? {n3}')
print(f'O valor digitado contém somente letras? {n4}')
print(f'O valor digitado contém letras e números? {n5}')
